In [1]:
import numpy as np

In [2]:
my_numpy_array = np.random.rand(3)

In [3]:
my_numpy_array

array([0.92788694, 0.22267188, 0.3045789 ])

In [4]:
type(my_numpy_array)

numpy.ndarray

In [5]:
my_numpy_array[0]

0.9278869413319689

In [6]:
import pandas as pd

In [7]:
my_series = pd.Series(my_numpy_array)

In [8]:
my_series

0    0.927887
1    0.222672
2    0.304579
dtype: float64

In [9]:
type(my_series)

pandas.core.series.Series

In [10]:
my_series[0]

0.9278869413319689

In [12]:
my_series = pd.Series(my_numpy_array, index=["First", "Second", "Third"])

In [13]:
my_series["Third"]

0.30457890118465036

In [14]:
my_series


First     0.927887
Second    0.222672
Third     0.304579
dtype: float64

In [15]:
my_series.index

Index(['First', 'Second', 'Third'], dtype='object')

In [16]:
array_2d = np.random.rand(3, 2)

In [17]:
array_2d

array([[0.4089759 , 0.18082994],
       [0.5193681 , 0.09586259],
       [0.02347411, 0.79607061]])

In [18]:
array_2d[1][1]

0.09586259059205748

In [19]:
array_2d[2][1]

0.7960706079392147

In [20]:
array_2d[2, 1]

0.7960706079392147

In [21]:
array_2d[2]

array([0.02347411, 0.79607061])

In [22]:
df = pd.DataFrame(array_2d)

In [23]:
df

0         1
0  0.408976  0.180830
1  0.519368  0.095863
2  0.023474  0.796071

In [25]:
df[1][1]

0.09586259059205748

In [26]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [27]:
df.columns = ["First", "Second"]

In [28]:
df

First    Second
0  0.408976  0.180830
1  0.519368  0.095863
2  0.023474  0.796071

In [32]:
df["First"]

0    0.408976
1    0.519368
2    0.023474
Name: First, dtype: float64

In [31]:
df["Second"]

0    0.180830
1    0.095863
2    0.796071
Name: Second, dtype: float64